<Project Sdk="Uno.Sdk">
    <PropertyGroup>
        <TargetFrameworks>
            net10.0-desktop;
            net10.0-browserwasm;
            net10.0-ios
        </TargetFrameworks>
        <OutputType>Exe</OutputType>
        <UnoSingleProject>true</UnoSingleProject>
        <LangVersion>14.0</LangVersion>
        <!-- Display name -->
        <ApplicationTitle>HorizonBudget</ApplicationTitle>
        <!-- App Identifier -->
        <ApplicationId>am.HorizonBudget</ApplicationId>
        <!-- Versions -->
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>
        <!-- Package Publisher -->
        <ApplicationPublisher>amaye</ApplicationPublisher>
        <!-- Package Description -->
        <Description>HorizonBudget powered by Uno Platform.</Description>

        <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
        <UnoFeatures>
            Material;
            Dsp;
            Hosting;
            Toolkit;
            Logging;
            MVUX;
            Configuration;
            HttpKiota;
            Serialization;
            Localization;
            Navigation;
            ThemeService;
            SkiaRenderer;
        </UnoFeatures>
    </PropertyGroup>
    <ItemGroup>
      <Compile Remove="Models\HorizonBudgetJsonContext.cs" />
    </ItemGroup>
    
    <ItemGroup>
        <TrimmerRootDescriptor Include="linker.xml" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Assets\Localization\" />
        <Folder Include="Resources\Styles\" />
        <Folder Include="ViewModels\" />
    </ItemGroup>
   
    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" />
      <PackageReference Include="Microsoft.Extensions.Configuration" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    </ItemGroup>
   
    <ItemGroup>
      <ProjectReference Include="..\HorizonBudget.Data\HorizonBudget.Data.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Page Update="Views\HomePage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="Views\DashboardPage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="Views\AboutPage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="Views\HelpPage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="Views\SettingsPage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>

</Project>
