<Project Sdk="Uno.Sdk">
    <PropertyGroup>
        <TargetFrameworks>
            net10.0-desktop;
            net10.0-browserwasm;
        </TargetFrameworks>
        <OutputType>WinExe</OutputType>
        <UnoSingleProject>true</UnoSingleProject>
        <LangVersion>14.0</LangVersion>
        <!-- Display name -->
        <ApplicationTitle>HorizonBudget</ApplicationTitle>
        <!-- App Identifier -->
        <ApplicationId>am.HorizonBudget</ApplicationId>
        <!-- Versions -->
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>
        <!-- Package Publisher -->
        <ApplicationPublisher>amaye</ApplicationPublisher>
        <!-- Package Description -->
        <Description>HorizonBudget powered by Uno Platform.</Description>

        <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
        <UnoFeatures>
            WinUI;
            Material;
            Dsp;
            Hosting;
            Toolkit;
            Logging;
            MVUX;
            Configuration;
            HttpKiota;
            Serialization;
            Localization;
            Navigation;
            ThemeService;
            SkiaRenderer;
        </UnoFeatures>
    </PropertyGroup>
    <ItemGroup>
      <Compile Remove="Resources\**" />
      <EmbeddedResource Remove="Resources\**" />
      <None Remove="Resources\**" />
    </ItemGroup>
    <ItemGroup>
      <Compile Remove="Models\HorizonBudgetJsonContext.cs" />
      <Compile Remove="Services\CategoryLookupFactory.cs" />
    </ItemGroup>
    
    <ItemGroup>
        <TrimmerRootDescriptor Include="linker.xml" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Assets\Localization\" />
    </ItemGroup>
   
    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" />
      <PackageReference Include="CommunityToolkit.WinUI.Extensions" />
      <PackageReference Include="Microsoft.Extensions.Configuration" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    </ItemGroup>
   
    <ItemGroup>
      <ProjectReference Include="..\HorizonBudget.Data\HorizonBudget.Data.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Page Update="Views\HomePage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="Views\DashboardPage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="Views\AboutPage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="Views\HelpPage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="Views\SettingsPage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
      <Page Update="Views\AccountsPage.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
    </ItemGroup>
    <ItemGroup>
      <Page Update="Views\ManageAccountPage.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
    </ItemGroup>
    <ItemGroup>
      <Content Remove="Resources\**" />
    </ItemGroup>
    <ItemGroup>
      <Page Remove="Resources\**" />
    </ItemGroup>
    <ItemGroup>
      <UpToDateCheckInput Remove="Resources\**" />
    </ItemGroup>
    <ItemGroup>
      <PRIResource Remove="Resources\**" />
    </ItemGroup>

</Project>
